name: Deploy Sample Application to AKS
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Login to ACR
      run: az acr login --name ${{ vars.ACR_REPO }} --username ${{ vars.ACR_REPO_USERNAME }} --password ${{ vars.ACR_REPO_PASSWORD }}
      
    - name: Build and Push Docker Image
      run: |
        docker build -t aks-deployment:latest .
        docker tag aks-deployment:latest acraksdeployment.azurecr.io/aks-deployment:latest
        docker push acraksdeployment.azurecr.io/aks-deployment:latest
        
    - name: Login and Deploy to AKS
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az login
          az account set --subscription ${{ vars.AKS_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group rg-aks-deployment-centralindia-01 --name aks-deployment-centralindia-01
          az aks install-cli
          echo "kubectl version --client"
          kubectl apply -f aks-deploy.yml
          kubectl apply -f aks-svc.yml
